[package]
name = "crypto_price"
version = "1.0.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.14", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
enum-iterator = "1.4.1"
serde_json = "1.0"
thiserror = "1"
